#!/usr/bin/env bash
set -euo pipefail
ref='4b2554d5b6064e8cd6e4b3ad5edb2a9eb214a6b9'
grep -Fq "container-release.yml@$ref" .github/workflows/container-release.yml
grep -Fq "contract-ref: $ref" .github/workflows/container-release.yml
grep -q "workflow_dispatch:" .github/workflows/container-release.yml
! grep -Eq '^  (push|pull_request):' .github/workflows/container-release.yml
grep -q 'VERJSON_RELEASE_TOKEN' .github/workflows/container-release.yml
test -f scripts/container_release_promotion.py
test -f scripts/container_release_manifest.py
test -f scripts/container_artifact_extract.py
printf '%s  %s\n' 'abe46ad22b6f51a4e8e60776ccf1b324a7227799de477091c76b713c54dac849' scripts/container_release_promotion.py | sha256sum --check --strict
printf '%s  %s\n' '8d3e5a49a682d9e36dc9e717ce2273a4ad73127ac019c9d3b5757eea2023f847' scripts/container_release_manifest.py | sha256sum --check --strict
printf '%s  %s\n' 'f485dcbf63dc15c530399f07cca876f398ab6520e932a2c1eb34deda1fef6748' scripts/container_artifact_extract.py | sha256sum --check --strict
grep -q 'Generated by Verjson/.github/scripts/gen-container-release.sh' .github/workflows/container-release.yml
echo 'container release contract passed'
