#!/usr/bin/env bash
set -Eeuo pipefail
# Generated by Verjson/.github/scripts/gen-container-deployment.sh; do not edit.
# Contract: 8c5718ac4b62aaf096d30e334cea93289fe42e33
#
# Every assertion reports what it expected and what it observed. A required
# contract test that exits 1 printing nothing forces an adopter to bisect this
# generated file by hand to find the unmet precondition
# (Verjson/verjson-git-runners#207). The reporting below only adds diagnostics:
# no assertion is relaxed, and the ERR trap re-exits with the original status so
# any assertion added later still fails closed, named by line.

contract_fail() {
  local reason="$*"
  # A reason is the whole point of the report; an assertion that supplies none
  # would print a bare "FAILED:" and send the adopter back to bisecting.
  [ -n "${reason//[[:space:]]/}" ] || reason="an assertion failed without naming a reason; this generated contract test is defective"
  printf 'container-deployment contract FAILED: %s\n' "$reason" >&2
  exit 1
}
trap 'contract_status=$?; printf "container-deployment contract FAILED: assertion at %s line %s exited %s\n" "$0" "$LINENO" "$contract_status" >&2; exit "$contract_status"' ERR

assert_digest() {
  local path="$1" expected="$2" observed
  [ -f "$path" ] || contract_fail "$path is missing (pinned sha256 $expected)"
  observed="$(sha256sum "$path" | cut -d' ' -f1)"
  [ "$observed" = "$expected" ] || contract_fail \
    "$path drifted from contract 8c5718ac4b62aaf096d30e334cea93289fe42e33: expected sha256 $expected, observed sha256 $observed"
}

assert_contains() {
  local path="$1" needle="$2"
  [ -f "$path" ] || contract_fail "$path is missing (expected to contain: $needle)"
  grep -qF -- "$needle" "$path" || contract_fail \
    "$path does not contain the required pinned text: $needle"
}

assert_digest .github/workflows/container-deployment.yml dbac3f3fa9634ca568bf3234336993a4c95c537df6a0a4ef2a3f4b085153e078
assert_digest scripts/container_deployment_controller.py 67cf863965f4d033c048e469fd9d0a2fed5f89660c3f84aa88711f9b5c97c7a7
assert_digest scripts/container_deployment_transport.py 1fd50ade2ce4fbceb349f3d3d3012653edd3fb38db3bd659e8865f012ebe0d67
assert_digest scripts/container_deployment_preflight.py 2cb3f4e19269b20588716c11853be2db29aeb4e43fd82259f543d43492c51836
assert_digest scripts/deployment-receipt.schema.json 079524c852e50e1a1675b11fd5d7d94aa4e3b0dc3e9cc0535c56c78c549689f4
assert_digest .github/workflows/container-deployment-code-review.yml 1a111e0cc175de1d66d09eb9bb1c0d0473c9ed3f3dc2c5b0cd94bfd961ae3066
assert_digest .github/workflows/container-deployment-security-review.yml 95bf15390f3fda1ffc4a9d9dcf1492e56ebffed6466734d08a3caa34c4ff6941
assert_digest .github/workflows/container-deployment-ai-review.yml b1b61de096a6e449e0f67d38ab478086396c95fc964e44dab9301b4eaa437185
assert_digest .github/workflows/container-deployment-review-producer.yml 44d2f6ef9a1c6ae669bd2fa5c8a707726ff931fc7c9451b026362124e1b2edd4
assert_digest scripts/container_deployment_review_producer.py e5877bd2d4fee84b8422de8e43903cac3d149a558af09a3d1e3a9c59a4bf9c45

[ -f "container-deployment.json" ] || contract_fail "deployment config container-deployment.json is missing"
# `-e` alone cannot reject a config with no JSON value at all: jq 1.6
# exits 0 on empty or whitespace-only input regardless of `-e` (#1617),
# because the filter never runs when there is nothing to run it against.
# Catch that case in plain bash before jq ever sees the file.
[ -s "container-deployment.json" ] || contract_fail "container-deployment.json is empty"
grep -q '[^[:space:]]' "container-deployment.json" || contract_fail "container-deployment.json contains only whitespace"
# The nine deployment-config preconditions are stated once. This program is both
# the verdict and the report: the contract passes iff it names no violation, so a
# condition added later cannot be enforced without also being diagnosed. `-e`
# keeps an empty or input-less config a rejection: jq yields no result at all for
# one, which is otherwise indistinguishable from "no violations found".
config_violations="$(jq -re '
  [
    (if .schemaVersion == 1 then empty else "schemaVersion: expected 1, observed \(.schemaVersion | tojson)" end),
    (if (.reviewAuthority | keys | sort == ["ai", "code", "security"]) then empty else "reviewAuthority: expected keys [ai, code, security], observed \(.reviewAuthority | keys? // null | tojson)" end),
    (if ([.reviewAuthority[].installationId] | all(type == "number" and . > 0)) then empty else "reviewAuthority[].installationId: expected positive numbers, observed \([.reviewAuthority[]?.installationId] | tojson)" end),
    (if (.reviewAuthority.ai.sourceAppId | type == "number" and . > 0) then empty else "reviewAuthority.ai.sourceAppId: expected a positive number, observed \(.reviewAuthority.ai.sourceAppId | tojson)" end),
    (if (.reviewAuthority.ai.sourceCheckName | type == "string" and length > 0) then empty else "reviewAuthority.ai.sourceCheckName: expected a non-empty string, observed \(.reviewAuthority.ai.sourceCheckName | tojson)" end),
   (if ((.hostEvidenceAuthority | type) == "object" and (.hostEvidenceAuthority | keys | sort) == ["appId", "installationId"] and (.hostEvidenceAuthority.appId | type) == "number" and .hostEvidenceAuthority.appId > 0 and (.hostEvidenceAuthority.installationId | type) == "number" and .hostEvidenceAuthority.installationId > 0) then empty else "hostEvidenceAuthority: expected positive host observation App and installation IDs" end),
(if ([.fleets[] | .hostEvidence] | all(type == "object" and (.doContext | type == "string" and length > 0) and (.doSshKey | type == "string" and length > 0) and (.maxAgeSeconds | type == "number" and . >= 1 and . <= 3600))) then empty else "fleets[].hostEvidence: expected read-only context, SSH key identity, and bounded max age" end),
 (if .cliCommand == ["verjson-cloud"] then empty else "cliCommand: expected [\"verjson-cloud\"], observed \(.cliCommand | tojson)" end),
    (if (.evidenceCommand | length == 2) then empty else "evidenceCommand: expected 2 elements, observed \(.evidenceCommand | tojson)" end),
    (if (.probeCommand | length == 2) then empty else "probeCommand: expected 2 elements, observed \(.probeCommand | tojson)" end),
    (if (.fleets | type == "object" and length > 0) then empty else "fleets: expected a non-empty object, observed \(.fleets | tojson)" end)
  ] | join("; ")
  ' "container-deployment.json" 2>/dev/null)" || contract_fail "container-deployment.json is not readable JSON"
[ -z "$config_violations" ] || contract_fail "$config_violations"
while IFS= read -r adapter; do
  [ -f "$adapter" ] || contract_fail \
    "container-deployment.json names adapter $adapter, which is not a regular file in this repository"
  [ ! -L "$adapter" ] || contract_fail \
    "container-deployment.json names adapter $adapter, which is a symlink; the contract requires a real file"
done < <(jq -r '.evidenceCommand[1], .probeCommand[1]' "container-deployment.json")
assert_contains .github/workflows/container-deployment.yml 'container-deployment.yml@8c5718ac4b62aaf096d30e334cea93289fe42e33'
assert_contains .github/workflows/container-deployment.yml 'contract-ref: 8c5718ac4b62aaf096d30e334cea93289fe42e33'
# The reusable jobs bind the caller's protected `production` environment, but an
# environment binding alone never resolves that environment's secrets inside a
# called workflow (ADR 0171, actions/runner#4453; git-runners run 36279086275
# reproduced it for the host-export credentials). The caller therefore carries
# exactly `secrets: inherit` on each reusable edge and still never names,
# maps, or forwards an individual secret (ADR 0198).
if forbidden="$(grep -En 'secrets\.|environment:|RUNNER_DEPLOY_TOKEN|DIGITALOCEAN_RUNNER_FLEET_TOKEN|GH_RUNNER_REGISTRATION_APP_PRIVATE_KEY|RUNNER_HOST_EVIDENCE_|:latest|:stable' \
  .github/workflows/container-deployment.yml)"; then
  contract_fail "$(printf '.github/workflows/container-deployment.yml must not name secrets, environments, or mutable tags; observed:\n%s' "$forbidden")"
fi
if named_secrets="$(grep -En 'secrets:' .github/workflows/container-deployment.yml | grep -Ev '^[0-9]+:    secrets: inherit$')"; then
  contract_fail "$(printf '.github/workflows/container-deployment.yml may carry only `secrets: inherit` on a reusable edge, never a named secret map; observed:\n%s' "$named_secrets")"
fi
[ "$(grep -Ec '^    secrets: inherit$' .github/workflows/container-deployment.yml)" = 1 ] || contract_fail \
  '.github/workflows/container-deployment.yml must inherit the caller secret context on exactly its one reusable edge (ADR 0171/0198)'
python3 -m py_compile scripts/container_deployment_controller.py scripts/container_deployment_preflight.py scripts/container_deployment_transport.py \
  || contract_fail "a pinned deployment python module failed to compile (see the traceback above)"
python3 -m json.tool scripts/deployment-receipt.schema.json >/dev/null \
  || contract_fail "scripts/deployment-receipt.schema.json is not valid JSON (see the error above)"
python3 - .github/workflows/container-deployment.yml <<'PY'
import sys
import yaml

with open(sys.argv[1], encoding="utf-8") as stream:
    workflow = yaml.safe_load(stream)
trigger = workflow.get("on", workflow.get(True))
assert set(trigger) == {"workflow_dispatch"}, (
    f"{sys.argv[1]}: expected exactly the workflow_dispatch trigger, observed {sorted(trigger)}"
)
job = workflow["jobs"]["deploy"]
assert set(job) == {"uses", "secrets", "with"}, (
    f"{sys.argv[1]}: deploy job expected exactly the keys ['secrets', 'uses', 'with'], observed {sorted(job)}"
)
assert job["secrets"] == "inherit", (
    f"{sys.argv[1]}: deploy job must inherit the caller secret context verbatim (ADR 0171/0198), observed {job['secrets']!r}"
)
assert job["uses"].startswith("Verjson/.github/.github/workflows/container-deployment.yml@"), (
    f"{sys.argv[1]}: deploy job expected to call the canonical container-deployment.yml, observed {job['uses']!r}"
)
observed_permissions = set(workflow["permissions"])
expected_permissions = {
    "actions", "attestations", "checks", "contents", "packages", "pull-requests"
}
assert observed_permissions == expected_permissions, (
    f"{sys.argv[1]}: expected permissions {sorted(expected_permissions)}, "
    f"observed {sorted(observed_permissions)}"
)
PY
