#!/usr/bin/env bash
# Prints the running log from the NEXT/ changelog fragments, newest first.
#
# Generated by Verjson/.github scripts/gen-changelog-caller.sh — do not edit by
# hand. Rendering is not implemented here: the canonical changelog contract
# lives in Verjson/.github (ADR 0038) and this repository pins one immutable
# commit of it, shared with .github/workflows/changelog.yml so that what you
# render locally is what CI validates.
set -euo pipefail

CONTRACT_REF="1486d44db0668d61354815c12bdbfc9d53fbeca4"

if [ "$#" -gt 0 ]; then
  echo "render-next: unexpected argument '$1'" >&2
  exit 2
fi

root="$(cd "$(dirname "$0")/.." && pwd)"
cache_dir="${XDG_CACHE_HOME:-$HOME/.cache}/verjson-changelog/$CONTRACT_REF"
contract="$cache_dir/changelog.py"

# Addressed by commit, so a cached copy cannot go stale: a new pin is a new path.
if [ ! -f "$contract" ]; then
  mkdir -p "$cache_dir"
  url="https://raw.githubusercontent.com/Verjson/.github/$CONTRACT_REF/scripts/changelog.py"
  # mktemp, not a fixed name: two concurrent renders share this cache directory.
  tmp="$(mktemp "$cache_dir/.changelog.XXXXXX")"
  if ! curl -fsSL "$url" -o "$tmp"; then
    rm -f "$tmp"
    echo "render-next: cannot fetch the changelog contract at $CONTRACT_REF" >&2
    exit 1
  fi
  mv "$tmp" "$contract"
fi

exec python3 "$contract" render-next --repo-root "$root"
